### ISSUE TITLE
Xhamster albums dont work 

### ISSUE THREAD

**Issue by grml32** [4pr0n/ripme#483]
Hi, xhamster galleries dont donwload anymore for me.
Tried two different PCs with no luck

Do they work for anyone else or they have stopped working for everyone ?

**Comment by cyian-1756** [comment]
What version of rip are you use?

Please you post the error log (if any)

Can you also post the url you're trying to rip?

**Comment by grml32** [comment]
Version is 1.4.4 
No xhamster gallery is ripped.
Just tried this https://xhamster.com/photos/gallery/4893071/jennifer_lopez.html

Here is the log:

[log.txt](https://github.com/4pr0n/ripme/files/853388/log.txt)

**Comment by cyian-1756** [comment]
It looks like XH just changed their cdn domain. It should be a simple fix

**Comment by grml32** [comment]
Can it be implemented in next version of ripme ?  :-)

**Comment by cyian-1756** [comment]
It can be, no idea if it will be tho.

**Comment by grml32** [comment]
There is no user editable part through which i can try to fix that myself, is there ?

**Comment by cyian-1756** [comment]
> There is no user editable part through which i can try to fix that myself, is there ?

Not really. 

You could clone my fork, checkout the xhamster branch and build it but that's a bit of work and I have no idea how to set up git/maven on windows

**Comment by grml32** [comment]
Ouch, doesnt sound easy.
Thanks for letting me know :-)

Hope someone fixes it in one of the next versions

**Comment by metaprime** [comment]
#484 should fix this.

**Comment by grml32** [comment]
Read #484 and it does not appear to be fixed or working.
Here is the log
[log.txt](https://github.com/4pr0n/ripme/files/867258/log.txt)

**Comment by cyian-1756** [comment]
@grml32 It's working fine for me, #484 was never merged because neither me nor metaprime can reproduce the bug. 

If I go to the urls in log.txt I get a redirect, but downloading the page with ripme works fine 

I'll keep debugging and seem if I can find the root cause of the issue

**Comment by cyian-1756** [comment]
@grml32 It looks like you and I are hitting different cdn domains, which is why I can download and you can't. I'm working on fixing it in my PR

**Comment by grml32** [comment]
Have you by any chance made a fix for this issue ? Still cannot use it :-(

**Comment by cyian-1756** [comment]
@grml32 My PR still hasn't been merged, I'll upload a .jar of my fork of ripme that you can use until my PR is merged.

**Comment by cyian-1756** [comment]
@grml32 

Here's the .jar of my fork https://github.com/cyian-1756/ripme/releases/download/1.4.2/ripme-1.4.2-unoffical-xhamster.zip

It should work, if not post the logs and I'll get on fixing it

**Comment by metaprime** [comment]
Fixed in https://github.com/4pr0n/ripme/pull/484 (merged)
